FORMAT: 1A
HOST: http://supermarket-warehouse.herokuapp.com/api/v1

# Super Market Divisi Warehouse

## Produk [/products]
### GET All Produk [GET]

+ Response 200 (application/json)
    {
    "status": true,
    "message": "Success",
    "results": [
        {
            "id_produk": 1,
            "kode_produk": "A11",
            "nama_produk": "Oreo Vanilla",
            "kategori": {
                "kode_kategori": "A1",
                "nama_kategori": "Makanan"
            },
            "deskripsi_produk": "Biskuit coklat dengan krim putih di tengahnya",
            "merk_produk": "Oreo",
            "tgl_produksi": "2019-12-31T17:00:00.000Z",
            "tgl_kadaluarsa": "2019-12-31T17:00:00.000Z",
            "created_at": "2020-12-01T17:12:18.000Z",
            "updated_at": "2020-12-01T17:12:18.000Z"
        },
        {
            "id_produk": 2,
            "kode_produk": "A22",
            "nama_produk": "Ultramilk Vanilla",
            "kategori": {
                "kode_kategori": "A2",
                "nama_kategori": "Minuman"
            },
            "deskripsi_produk": "Susu sapi rasa vanilla",
            "merk_produk": "Ultramilk",
            "tgl_produksi": "2020-01-31T17:00:00.000Z",
            "tgl_kadaluarsa": "2020-01-31T17:00:00.000Z",
            "created_at": "2020-12-01T17:12:18.000Z",
            "updated_at": "2020-12-01T17:12:18.000Z"
        }
    ]
}
## produk by kategori [/products/{kode_kategori}]
### GET All Produk By Category [GET]

+ Parameters
    + kode_kategori(required,string, `A11`)

+ Response 200 (application/json)
    {
    "status": true,
    "message": "Success",
    "results": [
        {
            "id_produk": 1,
            "kode_produk": "A11",
            "nama_produk": "Oreo Vanilla",
            "kategori": {
                "kode_kategori": "A1",
                "nama_kategori": "Makanan"
            },
            "deskripsi_produk": "Biskuit coklat dengan krim putih di tengahnya",
            "merk_produk": "Oreo",
            "tgl_produksi": "2019-12-31T17:00:00.000Z",
            "tgl_kadaluarsa": "2019-12-31T17:00:00.000Z",
            "created_at": "2020-12-01T17:12:18.000Z",
            "updated_at": "2020-12-01T17:12:18.000Z"
        },
        {
            "id_produk": 2,
            "kode_produk": "A22",
            "nama_produk": "Ultramilk Vanilla",
            "kategori": {
                "kode_kategori": "A2",
                "nama_kategori": "Minuman"
            },
            "deskripsi_produk": "Susu sapi rasa vanilla",
            "merk_produk": "Ultramilk",
            "tgl_produksi": "2020-01-31T17:00:00.000Z",
            "tgl_kadaluarsa": "2020-01-31T17:00:00.000Z",
            "created_at": "2020-12-01T17:12:18.000Z",
            "updated_at": "2020-12-01T17:12:18.000Z"
        }
    ]
}

## produk by id [/products/{id}]
### GET All Produk By Id [GET]

+ Parameters
    + id(required,number, `1`)

+ Response 200 (application/json)
    {
    "status": true,
    "message": "Success",
    "results": [
        {
            "id_produk": 1,
            "kode_produk": "A11",
            "nama_produk": "Oreo Vanilla",
            "kategori": {
                "kode_kategori": "A1",
                "nama_kategori": "Makanan"
            },
            "deskripsi_produk": "Biskuit coklat dengan krim putih di tengahnya",
            "merk_produk": "Oreo",
            "tgl_produksi": "2019-12-31T17:00:00.000Z",
            "tgl_kadaluarsa": "2019-12-31T17:00:00.000Z",
            "created_at": "2020-12-01T17:12:18.000Z",
            "updated_at": "2020-12-01T17:12:18.000Z"
        },
        {
            "id_produk": 2,
            "kode_produk": "A22",
            "nama_produk": "Ultramilk Vanilla",
            "kategori": {
                "kode_kategori": "A2",
                "nama_kategori": "Minuman"
            },
            "deskripsi_produk": "Susu sapi rasa vanilla",
            "merk_produk": "Ultramilk",
            "tgl_produksi": "2020-01-31T17:00:00.000Z",
            "tgl_kadaluarsa": "2020-01-31T17:00:00.000Z",
            "created_at": "2020-12-01T17:12:18.000Z",
            "updated_at": "2020-12-01T17:12:18.000Z"
        }
    ]
}


## Stok [/stock]
### GET stok [GET]
+ Response 200 (application/json)
    
        {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_stok": 1,
                    "produk_id": 3,
                    "jml_stok": 100,
                    "jml_prd_bagus": 95,
                    "jml_prd_cacat": 5,
                    "created_at": "0000-00-00 00:00:00",
                    "updated_at": "0000-00-00 00:00:00"
                }
            ]
        }        

## Stok By Month and Years [/stock/month]
### GET StokByMonth [GET]
+ Response 200 (application/json)
    
        {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_stok": 1,
                    "produk_id": 3,
                    "jml_stok": 100,
                    "jml_prd_bagus": 95,
                    "jml_prd_cacat": 5,
                    "created_at": "0000-00-00 00:00:00",
                    "updated_at": "0000-00-00 00:00:00"
                }
            ]
        } 
## Create Stok [/stock/create]         
### POST stok [POST]

+ Request
    {
        "produk_id":1,
        "jml_stok":10,
        "jml_prd_bagus":10,
        "jml_prd_cacat":10,
    }
+ Response 201 (application/json)

        {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_stok": 1,
                    "produk_id": 3,
                    "jml_stok": 100,
                    "jml_prd_bagus": 95,
                    "jml_prd_cacat": 5,
                    "created_at": "0000-00-00 00:00:00",
                    "updated_at": "0000-00-00 00:00:00"
                }
            ]
        }
## Update Stok [/stock/{id_stok}/update]        
### PUT stok [PUT]

+ Parameters
    + id_stok (required,integer,`4`)

+ Request
    {
        "produk_id":1,
        "jml_stok":10,
        "jml_prd_bagus":10,
        "jml_prd_cacat":10
    }

+ Response 201 (application/json)

        {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_stok": 1,
                    "produk_id": 3,
                    "jml_stok": 100,
                    "jml_prd_bagus": 95,
                    "jml_prd_cacat": 5,
                    "created_at": "0000-00-00 00:00:00",
                    "updated_at": "0000-00-00 00:00:00"
                }
            ]
        }
## Delete Stok [/stock/{id}/delete]
### DELETE [DELETE]

+ Parameters
    + id (required,integer, `1`)

+ Response 200 (application/json)

        {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_stok": 1
                }
            ]
        }

## Pengembalian Produk [/return]
### Get [GET]

+ Response 201 (application/json)

        {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_pengembalian": 1,
                    "produk_id": 3,
                    "keterangan": "Barang tidak sesuai",
                    "jml_produk": 5,
                    "tgl_pengajuan": "2020-11-30T17:00:00.000Z",
                    "tgl_pengembalian": "2020-12-02T17:00:00.000Z",
                    "created_at": "2020-12-17T15:19:33.000Z",
                    "updated_at": "2020-12-10T15:19:33.000Z"
                }
            ]
        }


## Update Pemgembalian Produk [/return/{id}/update]
### Put Pengembalian [PUT]

+ Parameters
    + id (required,integer,`1`)

+ Request
    {        
        "produk_id": 3,
        "keterangan": "Barang tidak sesuai",
        "jml_produk": 5,
        "tgl_pengajuan": "2020-11-30",
        "tgl_pengembalian": "2020-12-02",    
    }

+ Response 200 (application/json)

            {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_pengembalian": 1,
                    "produk_id": 3,
                    "keterangan": "Barang tidak sesuai",
                    "jml_produk": 5,
                    "tgl_pengajuan": "2020-11-30T17:00:00.000Z",
                    "tgl_pengembalian": "2020-12-02T17:00:00.000Z",
                    "created_at": "2020-12-17T15:19:33.000Z",
                    "updated_at": "2020-12-10T15:19:33.000Z"
                }
            ]
        }



## Hapus Pengembalian Produk [/return/{id}/delete]
### Delete [DELETE]

+ Parameters
    + id (required,integer,`1`)

+ Response 200 (application/json)

            {
            "status": true,
            "message": "success",
            "results": [
                {
                    "id_pengembalian": 1
                }
            ]
        }



## Create Pemgembalian Barang [/return/create]
### Post[POST]

+ Request
    {        
        "produk_id": 3,
        "keterangan": "Barang tidak sesuai",
        "jml_produk": 5,
        "tgl_pengajuan": "2020-11-30",
        "tgl_pengembalian": "2020-12-02"
    }
+ Response 200 (application/json)

            {
                "status": true,
                "message": "success",
                "results": [
                   
                ]
            }

## Get Notes [/notes]
###  GET [GET]

+ Response 200 (application/json)
        {
            "status":true,
            "message":"success",
            "results":[
                {
                    "id_pencatatan":4,
                    "status_id":4,
                    "produk_id":4,
                    "jml_produk":10,
                    "created_at": "2020-12-01T15:25:29.000Z",
                    "updated_at": "0000-00-00 00:00:00"
                }
            ]
        }

## Update Pencatatan Produl [/notes/{id}/update]
### put note [PUT]

+ Parameters
    + id (required,integer,`1`)
+ Request
    {     
        "status_id":4,
        "produk_id":4,
        "jml_produk":10
    }
+ Response 200 (application/json)

        [{
            "status":true,
            "message":"success",
            "results":[
                {
                    "id_pencatatan":4,
                    "status_id":4,
                    "produk_id":4,
                    "jml_produk":10,
                    "created_at": "2020-12-01T15:25:29.000Z",
                    "updated_at": "0000-00-00 00:00:00"
                }
            ]
        }     


## Hapus Pencatatan Produk [/note/{id}/delte]
### Delete [DELETE]

+ Parameters
    + id (required,integer,`1`)

+ Response 200 (application/json)

        {
            "status":true,
            "message":{
                "id_pencatatan":4,            
            }                            
        }

## Get All Categories [/categories]
### Get [GET]

+ Response 200 (application/json)

        [
            {
                "status": true,
                "message": "success",
                "results": [
                    {
                        "id": 1,
                        "kode_kategori": "mkn",
                        "nama_kategori": "Makanan"
                    },
                    {
                        "id": 2,
                        "kode_kategori": "mnm",
                        "nama_kategori": "Minuman"
                    }
                ]
            }
        ]

## Buat kategori [/catagory/create]
### POST [POST]

+ Request
    {
        "kodeKategori": "msk",
        "namaKategori": "Masker"
    }

+ Response 200 (application/json)
    [
        {
            "status": true,
            "message": "success",
            "results": {
                "kodeKategori": "msk",
                "namaKategori": "Masker"
            }
        }
    ]      
## Update kategori [/catagory/{id}/update]
### Update [PUT]

+ Parameters
    + id (required,integer,`1`)

+ Request
    {
        "kodeKategori": "msk",
        "namaKategori": "Masker"
    }   

+ Response 200 (application/json)
    [
        {
            "status": true,
            "message": "success",
            "results": {
                "kodeKategori": "msk",
                "namaKategori": "Maskerr"
            }
        }  
    ]   
## Hapus kategori by id [/category/{id}/delete]
### Delete [DELETE]

+ Parameters
    + id (required,integer,`1`)

+ Response 200 (application/json)
    [
        {
            "status": true,
            "message": "success",
            "results": ""
        }
    ]    
